### PR TITLE
1

### PR DESCRIPTION
**Pull request by lokibossever**
deploy Okex node on Mainnet on Akash.
SDL file + Readme (example post to check nodes via rpc)

### CODE REVIEW

**Comment by lokibossever** [comment]
version: "2.0"

services:
  okexchain:
    image: okexchain/fullnode-mainnet:v1.1.2
    expose:
      - port: 8545
        as: 8545
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 8192
        as: 8192
        to:
          - global: true
profiles:
  compute:
    okexchain-profile:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 1Gi
        storage:
          size: 32Gi
  placement:
    westcoast:
      pricing:
        okexchain-profile:
          denom: uakt
          amount: 1000
deployment:
  okexchain:
    westcoast:
      profile: okexchain-profile
      count: 1

**Comment by lokibossever** [comment]
`version: "2.0"

services:
  okexchain:
    image: okexchain/fullnode-mainnet:v1.1.2
    expose:
      - port: 8545
        as: 8545
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 8192
        as: 8192
        to:
          - global: true
profiles:
  compute:
    okexchain-profile:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 1Gi
        storage:
          size: 32Gi
  placement:
    westcoast:
      pricing:
        okexchain-profile:
          denom: uakt
          amount: 1000
deployment:
  okexchain:
    westcoast:
      profile: okexchain-profile
      count: 1`

**Comment by boz** [comment]
Hi @lokibossever - it looks like this pull request wasn't made correctly.  Look at the diffs.

If you edit it to include an Okex server then that'd be great.

**Comment by lokibossever** [comment]
Hello sir I am sorry for that
I will check it later
Thank you so much!

Adam Bozanich ***@***.***> 于 2022年3月20日周日 11:27写道：

**Comment by andy108369** [comment]
@lokibossever please open a new PR.

**Pull request closed without merging**
