### PR TITLE
Add RedPajama-INCITE-7B-Instruct

### PR DESCRIPTION
**Pull request by yuravorobei**
RedPajama-INCITE-7B-Instruct is a text generator

### CODE REVIEW

**Comment by Dimokus88** [comment]
@brewsterdrinkwater
There is a video, a good description and necessary links.
Looks ready to merge.

**Comment by Dimokus88** [comment]
@yuravorobei 
The content of your Dockerfile is different than the content of the 0.2 image in your Docker Hub.
Update information.
https://hub.docker.com/layers/yuravorobei/redpajama_incite_7b_instruct/0.2/images/sha256-f76b552bcee1f11b93b4d31200860c1fa2c0025aa5f160969b25757e70af6b87?context=explore

**Comment by yuravorobei** [comment]
@Dimokus88 
I pushed new image and updated files

**Comment by Dimokus88** [comment]
Seeing duplicate proposed deployment
https://github.com/akash-network/awesome-akash/pull/409/files#diff-7e50ca763f005231f77e375b2199922674ead8dc362e418ebdd0b75d3bc2d402
@andy108369

**Comment by yuravorobei** [comment]
> Seeing duplicate proposed deployment https://github.com/akash-network/awesome-akash/pull/409/files#diff-7e50ca763f005231f77e375b2199922674ead8dc362e418ebdd0b75d3bc2d402 @andy108369

These are both my deployments, I just got confused in the commits and branches

**Comment by Dimokus88** [comment]
> > Seeing duplicate proposed deployment https://github.com/akash-network/awesome-akash/pull/409/files#diff-7e50ca763f005231f77e375b2199922674ead8dc362e418ebdd0b75d3bc2d402 @andy108369
> 
> These are both my deployments, I just got confused in the commits and branches

Yeah, my head is spinning too, lol.
Maybe you can close this branch, since PR 409 contains a deploy with the image yuravorobei/redpajama_incite_7b_instruct:0.2

**Comment by yuravorobei** [comment]
I'm closing this request because this deployment is duplicated in my second deployment in PR 409 (https://github.com/akash-network/awesome-akash/pull/409)

**Pull request closed without merging**
