### PR TITLE
SDL for node deployment on Fuse Network

### PR DESCRIPTION
**Pull request by szymcio32**
SDL for node deployment (high resource) on Fuse Network

### CODE REVIEW

**Comment by andy108369** [comment]
@szymcio32 thank you for your PR.
Please update the top-level README.md file.

**Comment by szymcio32** [comment]
@andy108369 
updated

**Comment by andy108369** [comment]
@szymcio32  Thank you! Please add the last bit - `signedBy` attributes, e.g. https://github.com/akash-network/awesome-akash/blob/b720cd5/MySQL/deploy.yaml#L29-L32 to your deployment SDL manifest.

**Comment by szymcio32** [comment]
@andy108369 updated

**Review by andy108369 — APPROVED** [review]

**Pull request merged**
