### PR TITLE
AI-Image-App

### PR DESCRIPTION
**Pull request by alfset**
run Ai-image Apps with simple ui on akash

### CODE REVIEW

**Comment by Dimokus88** [comment]
deploy.yml is misspelled.
You need check and fix.
in README.md you need to add a link to the project repository, as well as a video with a working deployment.
Add your project's Dockerfile.
image

**Comment by alfset** [comment]
do i need fill pull request on whitelist address? my deployent has closed even i have ballance on wallet

**Comment by Dimokus88** [comment]
> do i need fill pull request on whitelist address? my deployent has closed even i have ballance on wallet

since deployments are carried out on a test network, they can be reset by the provider after some time of operation to free up resources.

**Comment by Dimokus88** [comment]
Extra lines here:

```yaml
     params:
       storage:
         data:
           mount: $(pwd)/data:/data
```
since we are not using persistent storage in the deployment, this part is not needed.

Further
```yaml
       signedBy:
         anyOf:
           -akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
           -akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
```
this part filters providers with auditing, relevant for the mainnet, but in the testnet we may not get rates due to this part of the code.

In addition, I do not see the GPU lease in the resources:
```yaml
     ai chat app:
       resources:
         cpu:
           units: 4
         memory:
           size: 12Gi
         storage:
           - size: 100Gi
```

Therefore, the image will not be generated.

**Comment by Dimokus88** [comment]
image
There is no evidence that the application uses the GPU when generating images.

**Comment by Dimokus88** [comment]
Hey @alfset !
Remove `- model: a100` in your sdl this includes selection by GPU type, but it works on other hardware as well, so it's redundant.
Check out your README.md, take as an example: https://github.com/urichPasser/awesome-akash/blob/5eb8b46dc42c33fa8b5e2be8d5c2531137eacb01/flan-t5-xxl/README.md

Make the same changes to the root README.md (https://github.com/akash-network/awesome-akash/blob/master/README.md), specify your application.

**Comment by Dimokus88** [comment]
resolve conflicts @alfset

**Pull request closed without merging**
