### PR TITLE
Add comfyui

### PR DESCRIPTION
**Pull request by zJuuu**
This PR adds support for ComfyUI on Akash Network

### CODE REVIEW

**Comment by anilmurty** [comment]
Thanks for this submission @zJuuu - tested it and it works. Just noted that there was no log output while the container was spinning up and eventually saw this (even though the comfyUI instance does come up)

[app]: 
[app]: 
[app]: 
[app]: --listen --port 8080 --gpu-only
[app]: WARNING:root:WARNING: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
[app]: Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop

Going to go ahead and merge this anyway

**Review by anilmurty — APPROVED** [review]

**Comment by anilmurty** [comment]
Oh, I see - because there are no checkpoints included by default (?)

Screenshot 2023-10-04 at 11 55 39 AM

**Comment by anilmurty** [comment]
Dowloaded checkpoints
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors.
https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors

and VAE
https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors

and Upscalers:
https://huggingface.co/uwg/upscaler/resolve/main/ESRGAN/4x_NMKD-Siax_200k.pth
https://huggingface.co/uwg/upscaler/resolve/main/ESRGAN/4x-UltraSharp.pth

And tried to run again. I get to the kSampler stage now and see this error:

Screenshot 2023-10-04 at 12 41 00 PM

**Comment by zJuuu** [comment]
@anilmurty tried to debug this but don't know the reason xformers is not working yet. It works if you add --disable-xformers to the command line flags as a workaround. I provide a fix in the next few days

**Comment by anilmurty** [comment]
separate weird issue I noted that only happens with this SDL (and I tested on mac). The Shell connects but tab-completion, text selection and bash history (up arrow to scroll history) don't work. Probably has to do with the bash config in the docker image (?) - will be great if these worked since devs that use this will want to download files and such through the CLI.

**Pull request merged**
