### PR TITLE
Deploy the `stable-diffusion-webui` On the Akash Network by Fogmeta Labs

### PR DESCRIPTION
**Pull request by hengdingy**
Deploy the `stable-diffusion-webui` On the Akash Network by Fogmeta Labs

### CODE REVIEW

**Comment by zJuuu** [comment]
Hello, could you include the Dockerfile you used and rename the file "READNE.md" to "README.md"?

**Comment by hengdingy** [comment]
No problem, I will submit my docker file @zJuuu

**Comment by hengdingy** [comment]
@zJuuu Done

**Comment by Dimokus88** [comment]
@brewsterdrinkwater
There is a video, a good description and necessary links.
Looks ready to merge.

**Comment by Dimokus88** [comment]
@hengdingy Since you are using the custom image `sxk1633/nvidia-cuda:11.4.0` in your **Dockerfile**, you also need to provide Dockerfile image  `sxk1633/nvidia-cuda:11.4.0` , so that we can make sure it is secure.

**Comment by hengdingy** [comment]
@Dimokus88 I have change it to the default image, it also works.  The custom image is convenient to test in the local machine.

 `FROM library/ubuntu:20.04`

**Comment by Dimokus88** [comment]
@hengdingy Modify the root README.md ( https://github.com/akash-network/awesome-akash/blob/master/README.md ) of the awesome-akash repository to include a link to your deployment and you're ready to merge.

**Comment by Dimokus88** [comment]
Ready to merge @brewsterdrinkwater !

**Comment by hengdingy** [comment]
@Dimokus88 I have updated the root readme, and it works.

**Comment by Dimokus88** [comment]
@hengdingy ,you have duplicate data, fix it as soon as possible.
image

**Comment by hengdingy** [comment]
@Dimokus88 sorry for late, I have fix it. thanks again

**Comment by Dimokus88** [comment]
Ready to merge @brewsterdrinkwater !

**Pull request merged**
