### PR TITLE
Witnesschain watchtower template

### PR DESCRIPTION
**Pull request by Shankusu993**
- Add Witness Chain Watchtower deployment template

### CODE REVIEW

**Comment by Dimokus88** [comment]
Hey @Shankusu993 !
Your PR looks awesome, ty!
But I think that your template can  be placed in the "blockchain" section, so as not to create a new "validators" section.
Let me know, what do you thing about this.

**Comment by Shankusu993** [comment]
Hey @Dimokus88 !

Thanks for the feedback. I believe the "Blockchain" section currently contains images for running validator/full nodes of various L1/other chains. The watchtower is not validator node for any specific blockchain, but more of a generic proof-of-location for any physical node (not necessarily blockchain node) connected to internet. Furthermore, in the future releases, it'll get capabilities to _watch_ for more physical attributes - like bandwidth, compute etc. 

I also think a broader 'Validator' section in-general can be useful for any other non-blockchain validator protocols (and outside witnesschain's watchtowers too). 

Let me know if this sounds reasonable, can otherwise put it under 'blockchain' as you recommended.

**Comment by Dimokus88** [comment]
Thank's @Shankusu993 !
Sounds reasonable.
On my end, the checks are complete and I believe the template is ready for merging.
If @anilmurty or @brewsterdrinkwater  are okay with adding a new section in root `README.md` , we can merge.

**Comment by anilmurty** [comment]
Hey @Shankusu993 - we already have a category called "Blockchain" - I think it makes sense to add WitnessChain Watchtower there

**Comment by Shankusu993** [comment]
Hey @anilmurty, thanks for your feedback. I've moved the watchtower to 'Blockchain' section. Would appreciate a second review :)

**Comment by anilmurty** [comment]
Thanks @Shankusu993 - changes look good, will approve and merge

**Pull request merged**
