### PR TITLE
Create Handshake Full Node Template

### PR DESCRIPTION
**Pull request by FliKites**
This template allows anyone to add a node to the peer to peer handshake DNS network. [handshake.org](https://handshake.org)

### CODE REVIEW

**Comment by 88plug** [comment]
Please add this to the README.md at the root of the repository. Thank you.

**Comment by andy108369** [comment]
@FliKites ping ...  ^^

**Comment by FliKites** [comment]
Ok. I'll get this done soon. Thanks for the ping.  ---- On Sat, 08 Apr 2023 13:59:19 -0400  ***@***.***  wrote ----
@FliKites ping ...  ^^

**Comment by FliKites** [comment]
@88plug @andy108369 This is good to go. Let me know if their are any issues.

**Comment by andy108369** [comment]
@FliKites please add the last bit - `signedBy` attributes, e.g. https://github.com/akash-network/awesome-akash/blob/b720cd5/MySQL/deploy.yaml#L29-L32

Thank you!

**Pull request merged**
