### PR TITLE
add defradb deployment

### PR DESCRIPTION
**Pull request by nasdf**

### CODE REVIEW

**Comment by Dimokus88** [comment]
Looks good and works, ready to merge.
@andy108369

**Comment by Dimokus88** [comment]
Hey @nasdf!
Just add Dockerfile

**Comment by nasdf** [comment]
> Hey @nasdf! Just add Dockerfile

Would this be a Dockerfile to build from source? We publish pre-built images to GitHub and DockerHub.

**Comment by Dimokus88** [comment]
Ready to merge @andy108369

**Review by andy108369 — APPROVED** [review]

**Pull request merged**
