### PR TITLE
chore: Update Llama 3.1 vllm image to v0.6.0

### PR DESCRIPTION
**Pull request by zJuuu**

### CODE REVIEW

**Comment by Dimokus88** [comment]
Hey @zJuuu !
Thanks for this PR!
I wanted to clarify that the part with `Llama-3.1-405B-master-list` will not be displayed correctly in `console.akash.network` and will not be visible to users.
For correct display we should stick to `deploy.yml` names for SDL files.
Is it possible for you to edit this in a form that will be available for syncing with `console.akash.network` ?

**Comment by zJuuu** [comment]
Hey @Dimokus88,
afaik the sdls in the `Llama-3.1-405B-master-list` are duplicates. I am not 100% sure yet though and would remove or edit the sdls in a future PR.

**Comment by anilmurty** [comment]
Yes, I left the master list for reference when I was moving things into their invididual folders. Totally fine if we want to delete it. Can we please get this merged in asap? We need to get these templates in a good place for demos this week

**Comment by Dimokus88** [comment]
Hey @anilmurty !
Overall, this PR has been tested and is **ready to merge**.
I just noted that one of the directories contains several sdl files that may not be displayed correctly in `console.akash` .

**Comment by anilmurty** [comment]
Thanks @zJuuu and @Dimokus88

**Review by anilmurty — APPROVED** [review]

**Pull request merged**
