### PR TITLE
ADD: Jekyll and Nextjs

### PR DESCRIPTION
**Pull request by Rashmi-278**

### CODE REVIEW

**Comment by boz** [comment]
Thanks for the contribution, @Rashmi-278 !

Can you add an entry to the top-level readme?

**Comment by Rashmi-278** [comment]
@boz  I have updated the top level readme, can we please merge this ?

**Comment by 88plug** [comment]
Jeckyll is super popular - upvote! @boz

**Comment by Rashmi-278** [comment]
@boz Pinging to merge

**Comment by andy108369** [comment]
@Rashmi-278 thank you for your PR.
There is already nextjs https://github.com/akash-network/awesome-akash/tree/master/nextjs
Please split the jekyll commit and make a separate PR.

**Pull request closed without merging**
