### PR TITLE
dria: add DKN compute node

### PR DESCRIPTION
**Pull request by vpavlin**
This PR adds recentrly launched [Dria](dria.co) Knowlesge Network compute node to the Awesome Akash repo. It allows deployers to join the network and execute assign tasks. 

There will be GPU support additions in the future

### CODE REVIEW

**Comment by Dimokus88** [comment]
Hey @vpavlin !
You can edit PR?

**Comment by vpavlin** [comment]
@Dimokus88 I can, what do you need edited?

**Comment by Dimokus88** [comment]
@vpavlin replace `latest` with the number versions. Akash providers cache images, so using `latest` may be a problem.

**Comment by vpavlin** [comment]
Hmm, on one hand I do agree with you, but then also for new deployments it is quite probably it will pull a the latest image (assuming not everyone picks the same provider and even then the deployment might happened on a new node). If people need to update or be sure what version they use, they can still modify the deployment, but I'd like to avoid the need to update this manifest with every push since the approval process is not straightforward here - unless I ping someone explicitly my PRs are usually unmerged:) So having `latest` there at least gives me hope in many cases the image used will actually be the latest:D

**Comment by andy108369** [comment]
> Hmm, on one hand I do agree with you, but then also for new deployments it is quite probably it will pull a the latest image (assuming not everyone picks the same provider and even then the deployment might happened on a new node). If people need to update or be sure what version they use, they can still modify the deployment, but I'd like to avoid the need to update this manifest with every push since the approval process is not straightforward here - unless I ping someone explicitly my PRs are usually unmerged:) So having `latest` there at least gives me hope in many cases the image used will actually be the latest:D

Hey @vpavlin, using `:latest` tags in Production is generally not recommended. Here’s why:

1. **Inconsistency:** The `:latest` tag can lead to inconsistencies, as `:latest` today might not be the same as `:latest` tomorrow. This means different environments could be running different versions without clear visibility.

2. **Caching Issues:** Akash aggressively caches images, including those tagged with `:latest`. Once an image is pulled on the Akash provider, it won’t be re-pulled there, which can unintentionally result in very-very outdated `:latest`-tagged images being used. This behavior with `:latest` tags is something I'm not a fan of, and I raised [this issue](https://github.com/akash-network/support/issues/50) back in 2021.

**Comment by andy108369** [comment]
@vpavlin FWIW: sometimes even non-`:latest`-tagged images go havoc, example https://github.com/akash-network/awesome-akash/pull/547 where we had to use the `sha256` digest manifest right after the image tag :roll_eyes:

**Comment by vpavlin** [comment]
Yeah, I understand all these - and I hate this behaviour, but Dria compute node is really early and being updated basically daily, so  `latest` is the best bet right now IMO - at least it makes it clear to users that if something is not working, they might want to check particular version. (that is my perception - I never trust `latest`:D)

I can also omit the tag altogether to indicate users should add some and it will default to `latest` if that helps:)

**Comment by vpavlin** [comment]
> @vpavlin FWIW: sometimes even non-`:latest`-tagged images go havoc, example #547 where we had to use the `sha256` digest manifest right after the image tag 🙄 (That was PITA to debug before we knew)

Absolutely, I tend to use shas in "production" deployments to make sure the image I deploy is actually the one I want, but again, that only makes sense for images and projects with reasonable release cycle, otherwise someone would have to send a PR here at least daily:) So I'd say keep `latest` and I'll add a note about it being still under fast decelopment and iterations and that users should check the latest image and use the `sha`?

**Comment by andy108369** [comment]
> Yeah, I understand all these - and I hate this behaviour, but Dria compute node is really early and being updated basically daily, so `latest` is the best bet right now IMO - at least it makes it clear to users that if something is not working, they might want to check particular version. (that is my perception - I never trust `latest`:D)
> 
> I can also omit the tag altogether to indicate users should add some and it will default to `latest` if that helps:)

@vpavlin It seems like there might be some confusion regarding the use of the "latest" image tags on Akash. As mentioned above, Akash aggressively caches images, which means that the "latest" tag on the providers may not actually correspond to the most recent version of the image. This discrepancy could lead to unexpected behavior during deployment, where the "latest" tag doesn't pull the newest version as intended.

To mitigate this, it is safer to specify exact image versions (or digests) to ensure that the desired image is deployed consistently across providers. This would help avoid any inconsistencies that could arise from Akash's image caching mechanism.
Could be a PITA when it comes to people running different "latest" tags.

I know that's another complication to keep updating the images each time in the SDL, but that's unfortunately the only way until this **non-default K8s behaviour** https://github.com/akash-network/support/issues/50 gets sorted.
As the compromise you could maybe add a link so people know where to obtain the actual most recent image tag (not the ":latest").

**Comment by andy108369** [comment]
You can use v0.1.4 tag
https://hub.docker.com/r/firstbatch/dkn-compute-node/tags

**Comment by vpavlin** [comment]
Yeah, yeah, I'll use the tags/hashes:-) Waiting for 0.1.5 to test it with GPUs and will update the PR

**Review by andy108369 — APPROVED** [review]

**Pull request merged**
