### PR TITLE
Feature/ssh bare images

### PR DESCRIPTION
**Pull request by ygrishajev**
Checkout the README in diff. It explains what's in this PR well

### CODE REVIEW

**Review by andy108369 — CHANGES_REQUESTED** [review]
@ygrishajev  Let's rename ubuntu-ssh into base-ssh ?

**Comment by ygrishajev** [comment]
> @ygrishajev Let's rename ubuntu-ssh into base-ssh ?

@andy108369 don't get it, what exactly? you mean the image? it's currently named `ubuntu-2404-ssh` which describes with it is. Any reason why would `base-ssh` be a better name?

**Comment by andy108369** [comment]
> > @ygrishajev Let's rename ubuntu-ssh into base-ssh ?
> 
> @andy108369 don't get it, what exactly? you mean the image? it's currently named `ubuntu-2404-ssh` which describes what it is. Any reason why would `base-ssh` be a better name?

I didn't mean the image name, sorry for not making it clear.
I meant just the directory name since you are adding Dockerfiles for different distros (centos, debian) under the "ubuntu-ssh" directory. "base-ssh" directory name would probably be more distro-agnostic, unless you have better ideas.
Hope that clarifies the intention.

**Comment by ygrishajev** [comment]
@andy108369 ah, yea, that makes more sense indeed. Just forgot to rename )

**Pull request merged**
