### PR TITLE
ID 5bshce3qiky00p0: Add 3 deployments to Machine Learning

### PR DESCRIPTION
**Pull request by wlouie1**
Adding a Machine Learning category, and adding 3 deployments to it:

1) Jupyter Notebook with Python Kernel - Deploys a full Jupyter environment (very popular amongst data scientists and ML practitioners) and includes an example notebook for training a deep neural network for handwritten digits recognition. See this blog for more details: https://wilsonlouie.medium.com/machine-learning-on-akash-decloud-part-1-3-training-cnn-on-mnist-using-tensorflow-be464f0f067e
{
  "services": {
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "cksvaauba98er5jrjcct2l6gm8.provider1.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {
    "web": [
      {
        "port": 6006,
        "externalPort": 30050,
        "proto": "TCP",
        "available": 1,
        "name": "web"
      }
    ]
  }
}

2) REST API endpoint for trained model inference, using TensorFlow Serving. See this blog for more details: https://wilsonlouie.medium.com/machine-learning-on-akash-decloud-part-2-3-tensorflow-model-serving-12e30d77a156
{
  "services": {
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "kn9kvjc2sd9t93e3g9btqohajs.provider3.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {}
}

3) Full Handwritten Digits Recognition Web Application. Front-end built with React, backend involves Nginx, Gunicorn, Flask, and TensorFlow. See this blog for more details: https://wilsonlouie.medium.com/machine-learning-on-akash-decloud-part-3-3-deploying-a-deep-learning-web-application-6a9e71e71dd1

I encourage you to play with this one! 5iuj38fuu9c5tej5t9i2s4c9pc.provider1.akashdev.net
{
  "services": {
    "flaskserver": {
      "name": "flaskserver",
      "available": 1,
      "total": 1,
      "uris": null,
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    },
    "tfserver": {
      "name": "tfserver",
      "available": 1,
      "total": 1,
      "uris": null,
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    },
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "5iuj38fuu9c5tej5t9i2s4c9pc.provider1.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {}
}

### CODE REVIEW

**Review by boz — APPROVED** [review]

**Review by troian — APPROVED** [review]

**Comment by wlouie1** [comment]
Hi, I noticed this has been approved a while ago but not merged. Up to you of course, but I believe showing that these ML-related deployments (training and serving, albeit on CPU right now) are possible even on the Akash Testnet would excite some people looking at this repo!

**Comment by boz** [comment]
Hi @wlouie1!  I'm so sorry for the delay.  I'd love to get this in, but would you mind updating the auditor key like is done in #185?

**Comment by andy108369** [comment]
@wlouie1 any updates please?

**Comment by andy108369** [comment]
fixed the signedBy & pricing bits => https://github.com/akash-network/awesome-akash/pull/374

**Pull request closed without merging**
