### PR TITLE
add vllm support

### PR DESCRIPTION
**Pull request by rakataprime**
adds vllm blog and deployment examples.  vllm is a multiuser llm server suitable for llm services with lots of concurrent users . @anilmurty

### CODE REVIEW

**Comment by anilmurty** [comment]
Thanks @rakataprime - as discussed on discord:
1. The model field wasn't getting populated in the UI - if that's expected we should make a note to the user and provide some instructions on how to get that working
2. In general, it'll be good to add some examples of both (UI and CLI) for how to use the app once it is deployed

**Comment by Dimokus88** [comment]
Hey @rakataprime !
Please, add info in root README.md about this template.

**Comment by rakataprime** [comment]
@Dimokus88 @anilmurty This should be good to go. I have made changes to SDL and added a troubleshooting guide

**Comment by rakataprime** [comment]
@anilmurty  can you merge this in now ?

**Review by anilmurty — APPROVED** [review]

**Pull request merged**
