### PR TITLE
Falcon7b

### PR DESCRIPTION
**Pull request by shimpa1**

### CODE REVIEW

**Comment by Dimokus88** [comment]
Awesome Shimpa!
It's work!

**Comment by Dimokus88** [comment]
Hey @shimpa1 !
Add a video of the deployment process and an extended description of the application with links to the main product to qualify for this assignment.

**Comment by Dimokus88** [comment]
Fixed.
Looks ready to merge @brewsterdrinkwater

**Comment by andy108369** [comment]
@shimpa1 please update the top-level readme file.

**Comment by Dimokus88** [comment]
Ready to merge @andy108369 @brewsterdrinkwater

**Pull request closed without merging**
